### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by a-breezy** [a-breezy/MoodRng#3]
Create Database:
- Make Schema file that includes tables for users
- Make sample seed file to for Database

'User' Table includes:
- User ID (unique primary)
- Username
- User first name
- User last name
- User password that has been encrypted

'Mood' Table includes
- Mood ID (unique primary)
- Mood Name
- Mood Emoji
- Mood color (perhaps this is another table?)

'Entries' Table (holds the entries for every user's moods) includes:
- Entry ID (unique primary)
- Username (foreign key to User ID)
- Mood (foreign key to Mood ID)
- Sleep
- Food
- Activities
- Extra description

**Comment by mloercher** [comment]
💥
